---
domain: logistics/generated_basic
domain_file: logistics/generated_domain.pddl
domain_name: logistics_zero_shot
n_instances: 220
start: 178
end: 200
instances_template: instance-{}.pddl
domain_intro: |
   I have to plan logistics to transport packages within cities via trucks and between cities via airplanes. Locations within a city are directly connected (trucks can move between any two such locations), and so are the cities. In each city there is exactly one truck and each city has one location that serves as an airport.
   Here are the actions that can be performed:

   Load a package into a truck. For example, load package_1 into truck_1 at location_1_1.
   Load a package into an airplane. For example, load package_1 into airplane_1 at location_1_1.
   Unload a package from a truck. For example, unload package_1 from truck_1 at location_1_1.
   Unload a package from an airplane. For example, unload package_1 from airplane_1 at location_1_1.
   Drive a truck from one location to another location. For example, drive truck_1 from location_1_1 to location_1_2 in city_1.
   Fly an airplane from one city to another city. For example, fly airplane_1 from location_1_1 to location_2_1. Here location_1_1 is the airport in city_1 and location_2_1 is the airport in city_2.

   The following are the restrictions on the actions:
   A package can be loaded into a truck only if the package and the truck are in the same location.
   Once a package is loaded into a truck, the package is not at the location and is in the truck.   
   A package can be loaded into an airplane only if the package and the airplane are in the same location.
   Once a package is loaded into an airplane, the package is not at the location and is in the airplane.
   A package can be unloaded from a truck only if the package is in the truck.
   Once a package is unloaded from a truck, the package is not in the truck and is at the location of the truck.
   A package can be unloaded from an airplane only if the package in the airplane.
   Once a package is unloaded from an airplane, the package is not in the airplane and is at the location of the airplane.   
   A truck can be driven from one location to another if the truck is at the from-location and both from-location and to-location are locations in the same city.
   Once a truck is driven from one location to another, it is not at the from-location and is at the to-location.
   An airplane can be flown from one city to another if the from-location and the to-location are airports and the airplane is at the from-location.
   Once an airplane is flown from one city to another the airplane is not at the from-location and is at the to-location.



domain_intro_cost: |
   I have to plan logistics to transport packages within cities via trucks and between cities via airplanes. Locations within a city are directly connected (trucks can move between any two such locations), and so are the cities. In each city there is exactly one truck and each city has one location that serves as an airport.
   Here are the actions that can be performed:

   Load a package into a truck. It takes one minute to do this action.
   Load a package into an airplane. It takes one minute to do this action.
   Unload a package from a truck. It takes one minute to do this action.
   Unload a package from an airplane. It takes one minute to do this action.
   Drive a truck from one location to another location. It takes two minutes to do this action.
   Fly an airplane from one city to another city. It takes five minutes to do this action.

   The following are the restrictions on the actions:
   A package can be loaded into a truck only if the package and the truck are in the same location.
   Once a package is loaded into a truck, the package is not at the location and is in the truck.   
   A package can be loaded into an airplane only if the package and the airplane are in the same location.
   Once a package is loaded into an airplane, the package is not at the location and is in the airplane.
   A package can be unloaded from a truck only if the package is in the truck.
   Once a package is unloaded from a truck, the package is not in the truck and is at the location of the truck.
   A package can be unloaded from an airplane only if the package in the airplane.
   Once a package is unloaded from an airplane, the package is not in the airplane and is at the location of the airplane.   
   A truck can be driven from one location to another if the truck is at the from-location and both from-location and to-location are locations in the same city.
   Once a truck is driven from one location to another, it is not at the from-location and is at the to-location.
   An airplane can be flown from one city to another if the from-location and the to-location are airports and the airplane is at the from-location.
   Once an airplane is flown from one city to another the airplane is not at the from-location and is at the to-location.


actions:
  {
    load-truck: "load {} into {} at {}",
    load-airplane: "load {} into {} at {}",
    unload-truck: "unload {} from {} at {}",
    unload-airplane: "unload {} from {} at {}",
    drive-truck: "drive {} from {} to {} in {}",
    fly-airplane: "fly {} from {} to {}"
  }

objects:
- blue block
- orange block
- red block
- yellow block

predicates: {
   # "airplane": "{} is an airplane",
   "airport": "{} is an airport",
   # "city": "{} is a city",
   # "location": "{} is a location",
   # "obj": "{} is a package",
   # "truck": "{} is a truck",
   "at": "{} is at {}",
   "in": "{} is in {}",
   "in-city": "{} is in the city {}",
  }

# encoded_objects: dictionary of object names, have to be alphabetical
encoded_objects:
  {"p": "package_{}", "t": "truck_{}", "a": "airplane_{}", "l": "location_{}_{}", "c": "city_{}"}
callbacks:
   - t1_gen_goal_directed_instances
